/*
 * Tech-Interactives Military Grade Radar System
 * Shared Configuration Header
 * Founder: Akhilesh TU
 */

#ifndef CONFIG_H
#define CONFIG_H

#define FIRMWARE_VERSION "1.0.0"
#define DEVICE_TYPE "ESP32-WROOM-32"

#define WIFI_SSID "YOUR_ROUTER_SSID"
#define WIFI_PASSWORD "YOUR_ROUTER_PASSWORD"
#define WIFI_CONNECT_TIMEOUT_MS 20000
#define WIFI_RECONNECT_INTERVAL_MS 5000

#define BACKEND_HOST "192.168.1.100"
#define BACKEND_PORT 5000
#define BROADCAST_PORT 12345
#define MAX_RECEIVERS 5
#define NETWORK_TIMEOUT_MS 30000

#define BROADCAST_INTERVAL_MS 100
#define CSI_TRANSMIT_INTERVAL_MS 500
#define HEALTH_CHECK_INTERVAL_MS 5000

#define PACKET_VERSION 1
#define PACKET_TYPE_TX 0x01
#define PACKET_TYPE_RX_CSI 0x02
#define PACKET_TYPE_HEALTH 0x03
#define MAX_CSI_SAMPLES 128

#define CSI_ENABLED 1
#define CSI_BUFFER_SIZE 2048

#define SIGNAL_FILTER_LENGTH 5
#define MOTION_THRESHOLD 0.3
#define PRESENCE_THRESHOLD 0.5

#define DEVICE_NAME_PREFIX "TI-Radar"

#define DEBUG_MODE 1
#define DEBUG_SERIAL_BAUD 115200

#define OTA_ENABLED 1
#define OTA_PORT 3232

#endif // CONFIG_H
